services:
  duckdb:
    build: .
    pull_policy: build
    command: db-${YEAR}-${MONTH}
    working_dir: /data
    volumes:
      - duckdb-data:/data
      - ../data/inputs/year=${YEAR}/month=${MONTH}:/inputs
      - ../data/outputs/year=${YEAR}/month=${MONTH}:/outputs

volumes:
  duckdb-data:
