services:
  vm:
    image: victoriametrics/victoria-metrics:v1.93.3
    # Default VictoriaMetrics retention period is 1 month.
    # Which is not suitable when you work with historical data.
    # VictoriaMetrics does not support indefinite retention, so we just set a very high duration.
    command: -retentionPeriod=100y
    ports:
      - 127.0.0.1:8428:8428/tcp
    volumes:
      - vm-data:/victoria-metrics-data
      - /snapshot

volumes:
  vm-data:
